### ISSUE TITLE
[BUG] Action with arrayed input parameter containing string enum yields to failed typer compilation

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Given an action such as:

```
    action   test( @mandatory array : array of {
        @mandatory testInput : String not null enum {
            anEntry;
        };
    } not null)
```

Yields to a failed compilation with the error message:

```
CDSError: Could not (re)generate types for model. Could not read file content of *: Failed: /[...]/node_modules/@cap-js/cds-typer/lib/cli.js "*" --outputDirectory "/[...]/@cds-models"
<exit code:>
1
<stderr:>
/[...]/node_modules/@cap-js/cds-typer/lib/util.js:69
        n = n.match(last)[0]
              ^

TypeError: n.match is not a function
    at Object.singular4 (/[...]/node_modules/@cap-js/cds-typer/lib/util.js:69:15)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:376:46)
    at Resolver.resolveAndRequire (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:220:31)
    at StructuredInlineDeclarationResolver.visitElement (/[...]/node_modules/@cap-js/cds-typer/lib/components/inline.js:70:44)
    at Visitor.visitElement (/[...]/node_modules/@cap-js/cds-typer/lib/visitor.js:459:47)
    at StructuredInlineDeclarationResolver.resolveInlineDeclaration (/[...]/node_modules/@cap-js/cds-typer/lib/components/inline.js:43:57)
    at #resolveInlineDeclarationType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:425:55)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:396:47)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:392:18)
    at Resolver.resolveAndRequire (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:220:31)

Node.js v20.10.0
CDSError: Could not (re)generate types for model. Could not read file content of *: Failed: /[...]/node_modules/@cap-js/cds-typer/lib/cli.js "*" --outputDirectory "/[...]/@cds-models"
<exit code:>
1
<stderr:>
/[...]/node_modules/@cap-js/cds-typer/lib/util.js:69
        n = n.match(last)[0]
              ^

TypeError: n.match is not a function
    at Object.singular4 (/[...]/node_modules/@cap-js/cds-typer/lib/util.js:69:15)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:376:46)
    at Resolver.resolveAndRequire (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:220:31)
    at StructuredInlineDeclarationResolver.visitElement (/[...]/node_modules/@cap-js/cds-typer/lib/components/inline.js:70:44)
    at Visitor.visitElement (/[...]/node_modules/@cap-js/cds-typer/lib/visitor.js:459:47)
    at StructuredInlineDeclarationResolver.resolveInlineDeclaration (/[...]/node_modules/@cap-js/cds-typer/lib/components/inline.js:43:57)
    at #resolveInlineDeclarationType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:425:55)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:396:47)
    at Resolver.resolveType (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:392:18)
    at Resolver.resolveAndRequire (/[...]/node_modules/@cap-js/cds-typer/lib/components/resolver.js:220:31)

Node.js v20.10.0
```

### Expected Behavior

I'd expect the compilation to work.

### Environment

```markdown
- **OS**: MacOs
- **Node**: v20.10.0.
- **npm**:
- **cds-typer**: 0.13.0
- **cds**:7.4.2
```

**Comment by daogrady** [comment]
Hi Tobias,

this one is surprisingly less benign than scalar enum types for action parameters. I have opted to instead use the encapsulating type for now. I.e. instead of a fully type-safe parameter type `'A' | 'B' | 'C'` you'll get `string`. But it should at least compile now. Feel free to try it out before I merge.

Best,
Daniel
