### ISSUE TITLE
[BUG] New data type `cds.Vector` not supported

### ISSUE THREAD

**Issue by niklasvieth** [cap-js/cds-typer#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Using the new `cds.Vector` type, the type generation fails.
see https://pages.github.tools.sap/cap/docs/releases/mar24#sap-hana-cloud-vector-engine

### Expected Behavior

Type generation should not fail.

### Steps To Reproduce

```cds
entity TestEntity {
    key ID        : UUID;
        embedding : Vector(1536)
}
```
run 

```sh
npx @cap-js/cds-typer "*"
```

Resulting error
```sh 
/@cap-js/cds-typer/lib/components/resolver.js:569
            throw new Error(`Can not resolve apparent builtin type '${t}' to any CDS type.`)
                  ^

Error: Can not resolve apparent builtin type 'cds.Vector' to any CDS type.
    at #resolveTypeName (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/components/resolver.js:569:19)
    at Resolver.resolvePotentialReferenceType (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/components/resolver.js:551:34)
    at Resolver.resolveType (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/components/resolver.js:490:22)
    at Resolver.resolveAndRequire (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/components/resolver.js:302:31)
    at StructuredInlineDeclarationResolver.visitElement (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/components/inline.js:70:44)
    at Visitor.visitElement (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/visitor.js:487:47)
    at Visitor.<anonymous> (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/visitor.js:172:26)
    at Buffer.addIndented (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/file.js:495:13)
    at Buffer.addIndentedBlock (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/file.js:510:14)
    at Visitor.<anonymous> (/Users/D067852/Code/SBB/sbb-chatbot/node_modules/@cap-js/cds-typer/lib/visitor.js:165:20)
```

### Environment

```markdown
- **OS**: MACOS
- **Node**: `v20.5.1` 
- **npm**: `9.8.0`
- **cds-typer**: `v20.5.1` 
- **cds**: @sap/cds: `7.8.0`
```

**Comment by daogrady** [comment]
Hi Niklas,

thanks for pointing out this missing builtin type! I checked the internals of `@sap/cds` and this new type seems to effectively be a `string`, so I would address this by representing all `cds.Vector` properties as TypeScript `string`s. Will this cover your use cases?

Best,
Daniel

**Comment by daogrady** [comment]
Great! I will include this in a small release which I plan to ready up before the upcoming holidays.
