### ISSUE TITLE
[QUESTION] Why entity.association('*') is not same as entity?.association?.('*') in cds-typer?

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-typer#312]
### Question

HI! I have q very weird issue in my project.

Let's say i have a code like this:
```ts
const result = await SELECT.from(OBJECTS, (o) => {
    o.OBJECT_TYPE, o.OBJECT_OID, o.SCHEMA_NAME, o.OBJECT_NAME;
    o.view &&
      o.view((v) => {
        v('*');
        v.columns('*');
      });
```

By default it won't run because of the TS error:
```
Cannot invoke an object which is possibly 'undefined'.ts(2722)
(property) columns?: cds.ql.QLExtensions_<VIEW_COLUMNS_> | undefined
```

So here are two possible ways how to solve it:

- using condition
```
 o.view((v) => {
        v('*');
        v.columns && v.columns('*');
      });
```

and it works 

- using optional notation ( also preferred by AI )

```
  o.view &&
      o.view((v) => {
        v('*');
        v?.columns?.('*');
      });
```

and this doesn't work!

Here is what I have in the console:
```
/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876
        throw new Error(
              ^
Error: "call" not found in the elements of "VIEWS"
    at stepNotFoundInCombinedElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876:15)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:576:13
    at Array.forEach (<anonymous>)
    at inferQueryElement (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:529:18)
    at handleRef (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:453:7)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:331:16
    at Array.forEach (<anonymous>)
    at inferQueryElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:300:15)
    at infer (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:71:22)
    at resolveExpand (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:842:42)
```

Do you know why? Thank you!

**Comment by ThePlenkov** [comment]
@chgeo  do you know why? Can it be a bug? Thanks!
